version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: shipilenok/foodgram_backend
    env_file: .env
    volumes:
      - static:/static/
      - media:/app/media/
      - ./data:/app/data/

  frontend:
    image: shipilenok/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  nginx:
    image: shipilenok/foodgram_gateway
    ports:
      - "8000:80"
    volumes:
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/static/
      - media:/app/media/
