version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data/

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - static:/static/
      - media:/app/media/
      - ./data:/app/data/

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  nginx:
    build: ./infra/
    ports:
      - "8000:80"
    volumes:
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/static/
      - media:/app/media/
